"""System pre-defined providers and models (migrated from Octopus)."""

SYSTEM_PROVIDERS = [
    {
        "id": "cherryin",
        "display_name": "CherryIN",
        "provider_type": "openai",
        "api_base": "https://open.cherryin.net",
        "default_model": "",
        "models": [],
    },
    {
        "id": "silicon",
        "display_name": "Silicon",
        "provider_type": "openai",
        "api_base": "https://api.siliconflow.cn",
        "default_model": "",
        "models": [],
    },
    {
        "id": "aihubmix",
        "display_name": "AiHubMix",
        "provider_type": "openai",
        "api_base": "https://aihubmix.com",
        "default_model": "gpt-5",
        "models": [
            {"id": "gpt-5", "name": "gpt-5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-mini", "name": "gpt-5-mini", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-nano", "name": "gpt-5-nano", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-chat-latest", "name": "gpt-5-chat-latest", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "o3", "name": "o3", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "o4-mini", "name": "o4-mini", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-4.1", "name": "gpt-4.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-4o", "name": "gpt-4o", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-image-1", "name": "gpt-image-1", "model_type": "image", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "DeepSeek-V3", "name": "DeepSeek-V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "DeepSeek-R1", "name": "DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "claude-sonnet-4-20250514", "name": "claude-sonnet-4-20250514", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-pro", "name": "gemini-2.5-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-flash-nothink", "name": "gemini-2.5-flash-nothink", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-flash", "name": "gemini-2.5-flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "Qwen3-235B-A22B-Instruct-2507", "name": "Qwen3-235B-A22B-Instruct-2507", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-0711-preview", "name": "kimi-k2-0711-preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Llama-4-Scout-17B-16E-Instruct", "name": "Llama-4-Scout-17B-16E-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Llama-4-Maverick-17B-128E-Instruct-FP8", "name": "Llama-4-Maverick-17B-128E-Instruct-FP8", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "zhipu",
        "display_name": "智谱AI",
        "provider_type": "openai",
        "api_base": "https://open.bigmodel.cn/api/paas/v4",
        "default_model": "glm-5",
        "models": [
            {"id": "glm-5", "name": "GLM-5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.7", "name": "GLM-4.7", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.5-flash", "name": "GLM-4.5-Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.6", "name": "GLM-4.6", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.6v", "name": "GLM-4.6V", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "glm-4.6v-flash", "name": "GLM-4.6V-Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "glm-4.6v-flashx", "name": "GLM-4.6V-FlashX", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "glm-4.5", "name": "GLM-4.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.5-air", "name": "GLM-4.5-Air", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.5-airx", "name": "GLM-4.5-AirX", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "glm-4.5v", "name": "GLM-4.5V", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "embedding-3", "name": "Embedding-3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "zai",
        "display_name": "Z.ai",
        "provider_type": "openai",
        "api_base": "https://api.z.ai/api/paas/v4",
        "default_model": "",
        "models": [],
    },
    {
        "id": "deepseek",
        "display_name": "DeepSeek",
        "provider_type": "openai",
        "api_base": "https://api.deepseek.com",
        "default_model": "deepseek-chat",
        "models": [
            {"id": "deepseek-chat", "name": "DeepSeek V3", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-reasoner", "name": "DeepSeek R1", "model_type": "chat", "context_window": 128000, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "openai",
        "display_name": "OpenAI",
        "provider_type": "openai-response",
        "api_base": "https://api.openai.com",
        "default_model": "gpt-5.4",
        "models": [
            {"id": "gpt-5.4", "name": "GPT 5.4", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.4-pro", "name": "GPT 5.4 Pro", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.2", "name": "GPT 5.2", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.2-pro", "name": "GPT 5.2 Pro", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.1", "name": "GPT 5.1", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5", "name": "GPT 5", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-pro", "name": "GPT 5 Pro", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-chat", "name": "GPT 5 Chat", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-image-1", "name": "GPT Image 1", "model_type": "image", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "anthropic",
        "display_name": "Anthropic",
        "provider_type": "anthropic",
        "api_base": "https://api.anthropic.com",
        "default_model": "claude-opus-4-6",
        "models": [
            {"id": "claude-opus-4-6", "name": "Claude Opus 4.6", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-sonnet-4-6", "name": "Claude Sonnet 4.6", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-sonnet-4-5", "name": "Claude Sonnet 4.5", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-haiku-4-5", "name": "Claude Haiku 4.5", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-opus-4-5", "name": "Claude Opus 4.5", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
        ],
    },
    {
        "id": "azure-openai",
        "display_name": "Azure OpenAI",
        "provider_type": "azure-openai",
        "api_base": "",
        "default_model": "gpt-4o",
        "models": [
            {"id": "gpt-4o", "name": "GPT-4o", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4o-mini", "name": "GPT-4o-mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "gemini",
        "display_name": "Google Gemini",
        "provider_type": "gemini",
        "api_base": "https://generativelanguage.googleapis.com",
        "default_model": "gemini-2.5-flash",
        "models": [
            {"id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-2.5-flash-image-preview", "name": "Gemini 2.5 Flash Image", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-3-pro-image-preview", "name": "Gemini 3 Pro Image Preview", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-3-pro-preview", "name": "Gemini 3 Pro Preview", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-3.1-pro-preview", "name": "Gemini 3.1 Pro Preview", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
        ],
    },
    {
        "id": "vertexai",
        "display_name": "Vertex AI",
        "provider_type": "vertexai",
        "api_base": "",
        "default_model": "",
        "models": [],
    },
    {
        "id": "ollama",
        "display_name": "Ollama",
        "provider_type": "ollama",
        "api_base": "http://localhost:11434",
        "default_model": "",
        "models": [],
    },
    {
        "id": "lmstudio",
        "display_name": "LM Studio",
        "provider_type": "openai",
        "api_base": "http://localhost:1234",
        "default_model": "",
        "models": [],
    },
    {
        "id": "openrouter",
        "display_name": "OpenRouter",
        "provider_type": "openai",
        "api_base": "https://openrouter.ai/api/v1",
        "default_model": "google/gemini-2.5-flash-image-preview",
        "models": [
            {"id": "google/gemini-2.5-flash-image-preview", "name": "Google: Gemini 2.5 Flash Image", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "google/gemini-2.5-flash-preview", "name": "Google: Gemini 2.5 Flash Preview", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "qwen/qwen-2.5-7b-instruct:free", "name": "Qwen: Qwen-2.5-7B Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek/deepseek-chat", "name": "DeepSeek: V3", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "mistralai/mistral-7b-instruct:free", "name": "Mistral: Mistral 7B Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "groq",
        "display_name": "Groq",
        "provider_type": "openai",
        "api_base": "https://api.groq.com/openai",
        "default_model": "llama3-8b-8192",
        "models": [
            {"id": "llama3-8b-8192", "name": "LLaMA3 8B", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "llama3-70b-8192", "name": "LLaMA3 70B", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "mistral-saba-24b", "name": "Mistral Saba 24B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gemma-9b-it", "name": "Gemma 9B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "mistral",
        "display_name": "Mistral",
        "provider_type": "openai",
        "api_base": "https://api.mistral.ai",
        "default_model": "pixtral-12b-2409",
        "models": [
            {"id": "pixtral-12b-2409", "name": "Pixtral 12B [Free]", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "pixtral-large-latest", "name": "Pixtral Large", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "ministral-3b-latest", "name": "Mistral 3B [Free]", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ministral-8b-latest", "name": "Mistral 8B [Free]", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "codestral-latest", "name": "Mistral Codestral", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "mistral-large-latest", "name": "Mistral Large", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "mistral-small-latest", "name": "Mistral Small", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "open-mistral-nemo", "name": "Mistral Nemo", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "mistral-embed", "name": "Mistral Embedding", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "github",
        "display_name": "Github Models",
        "provider_type": "openai",
        "api_base": "https://models.github.ai/inference",
        "default_model": "gpt-4o",
        "models": [
            {"id": "gpt-4o", "name": "OpenAI GPT-4o", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "copilot",
        "display_name": "Github Copilot",
        "provider_type": "openai",
        "api_base": "https://api.githubcopilot.com",
        "default_model": "gpt-4o-mini",
        "models": [
            {"id": "gpt-4o-mini", "name": "OpenAI GPT-4o-mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "moonshot",
        "display_name": "Moonshot AI",
        "provider_type": "openai",
        "api_base": "https://api.moonshot.cn",
        "default_model": "moonshot-v1-auto",
        "models": [
            {"id": "moonshot-v1-auto", "name": "moonshot-v1-auto", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-0711-preview", "name": "kimi-k2-0711-preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2.5", "name": "Kimi K2.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-0905-Preview", "name": "Kimi K2 0905 Preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-turbo-preview", "name": "Kimi K2 Turbo Preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-thinking", "name": "Kimi K2 Thinking", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "kimi-k2-thinking-turbo", "name": "Kimi K2 Thinking Turbo", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "baichuan",
        "display_name": "百川智能",
        "provider_type": "openai",
        "api_base": "https://api.baichuan-ai.com",
        "default_model": "Baichuan4",
        "models": [
            {"id": "Baichuan4", "name": "Baichuan4", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan3-Turbo", "name": "Baichuan3 Turbo", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan3-Turbo-128k", "name": "Baichuan3 Turbo 128k", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan4-Turbo", "name": "Baichuan4 Turbo", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan4-Air", "name": "Baichuan4 Air", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan-M2", "name": "Baichuan M2", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan-M2-Plus", "name": "Baichuan M2 Plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan-M3", "name": "Baichuan M3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Baichuan-M3-Plus", "name": "Baichuan M3 Plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "dashscope",
        "display_name": "阿里云百炼",
        "provider_type": "openai",
        "api_base": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "default_model": "qwen-vl-plus",
        "models": [
            {"id": "qwen-vl-plus", "name": "qwen-vl-plus", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "qwen-coder-plus", "name": "qwen-coder-plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-flash", "name": "qwen-flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-plus", "name": "qwen-plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-max", "name": "qwen-max", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen3-max", "name": "qwen3-max", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen3.5-plus", "name": "qwen3.5-plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen3.5-397b-a17b", "name": "qwen3.5-397b-a17b", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "text-embedding-v4", "name": "text-embedding-v4", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-v3", "name": "text-embedding-v3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-v2", "name": "text-embedding-v2", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-v1", "name": "text-embedding-v1", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "qwen3-rerank", "name": "qwen3-rerank", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "stepfun",
        "display_name": "阶跃星辰",
        "provider_type": "openai",
        "api_base": "https://api.stepfun.com",
        "default_model": "step-1-8k",
        "models": [
            {"id": "step-1-8k", "name": "Step 1 8K", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "step-1-flash", "name": "Step 1 Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "doubao",
        "display_name": "豆包",
        "provider_type": "openai",
        "api_base": "https://ark.cn-beijing.volces.com/api/v3",
        "default_model": "doubao-seed-1-8-251228",
        "models": [
            {"id": "doubao-seed-1-8-251228", "name": "Doubao-Seed-1.8", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-1-5-vision-pro-32k-250115", "name": "doubao-1.5-vision-pro", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "doubao-1-5-pro-32k-250115", "name": "doubao-1.5-pro-32k", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-1-5-pro-32k-character-250228", "name": "doubao-1.5-pro-32k-character", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-1-5-pro-256k-250115", "name": "Doubao-1.5-pro-256k", "model_type": "chat", "context_window": 262144, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-250120", "name": "DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-distill-qwen-32b-250120", "name": "DeepSeek-R1-Distill-Qwen-32B", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-distill-qwen-7b-250120", "name": "DeepSeek-R1-Distill-Qwen-7B", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3-250324", "name": "DeepSeek-V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-pro-32k-241215", "name": "Doubao-pro-32k", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-pro-32k-functioncall-241028", "name": "Doubao-pro-32k-functioncall", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-pro-32k-character-241215", "name": "Doubao-pro-32k-character", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-pro-256k-241115", "name": "Doubao-pro-256k", "model_type": "chat", "context_window": 262144, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-lite-4k-character-240828", "name": "Doubao-lite-4k-character", "model_type": "chat", "context_window": 4096, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-lite-32k-240828", "name": "Doubao-lite-32k", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-lite-32k-character-241015", "name": "Doubao-lite-32k-character", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-lite-128k-240828", "name": "Doubao-lite-128k", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-1-5-lite-32k-250115", "name": "Doubao-1.5-lite-32k", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-embedding-large-text-240915", "name": "Doubao-embedding-large", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "doubao-embedding-text-240715", "name": "Doubao-embedding", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "doubao-embedding-vision-241215", "name": "Doubao-embedding-vision", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "doubao-vision-lite-32k-241015", "name": "doubao-vision-lite-32k", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "doubao-seed-2-0-pro-260215", "name": "Doubao-Seed-2.0-Pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-seed-2-0-lite-260215", "name": "Doubao-Seed-2.0-Lite", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-seed-2-0-code-preview-260215", "name": "Doubao-Seed-2.0-Code-Preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "doubao-seed-2-0-mini-260215", "name": "Doubao-Seed-2.0-Mini", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "minimax",
        "display_name": "MiniMax",
        "provider_type": "openai",
        "api_base": "https://api.minimax.chat/v1",
        "default_model": "MiniMax-M2.5",
        "models": [
            {"id": "MiniMax-M2.5", "name": "MiniMax-M2.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.5-highspeed", "name": "MiniMax-M2.5-highspeed", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.5-lightning", "name": "MiniMax-M2.5-lightning", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.1", "name": "MiniMax-M2.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.1-lightning", "name": "MiniMax-M2.1-lightning", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2", "name": "MiniMax-M2", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "M2-her", "name": "M2-her", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "minimax-global",
        "display_name": "MiniMax Global",
        "provider_type": "openai",
        "api_base": "https://api.minimax.io/v1",
        "default_model": "MiniMax-M2.5",
        "models": [
            {"id": "MiniMax-M2.5", "name": "MiniMax-M2.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.5-highspeed", "name": "MiniMax-M2.5-highspeed", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.5-lightning", "name": "MiniMax-M2.5-lightning", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.1", "name": "MiniMax-M2.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2.1-lightning", "name": "MiniMax-M2.1-lightning", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "MiniMax-M2", "name": "MiniMax-M2", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "M2-her", "name": "M2-her", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "fireworks",
        "display_name": "Fireworks AI",
        "provider_type": "openai",
        "api_base": "https://api.fireworks.ai/inference",
        "default_model": "accounts/fireworks/models/mythomax-l2-13b",
        "models": [
            {"id": "accounts/fireworks/models/mythomax-l2-13b", "name": "mythomax-l2-13b", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "accounts/fireworks/models/llama-v3-70b-instruct", "name": "Llama-3-70B-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "together",
        "display_name": "Together AI",
        "provider_type": "openai",
        "api_base": "https://api.together.xyz",
        "default_model": "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo",
        "models": [
            {"id": "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo", "name": "Llama-3.2-11B-Vision", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo", "name": "Llama-3.2-90B-Vision", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "google/gemma-2-27b-it", "name": "gemma-2-27b-it", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "google/gemma-2-9b-it", "name": "gemma-2-9b-it", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "nvidia",
        "display_name": "NVIDIA NIM",
        "provider_type": "openai",
        "api_base": "https://integrate.api.nvidia.com",
        "default_model": "01-ai/yi-large",
        "models": [
            {"id": "01-ai/yi-large", "name": "yi-large", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "meta/llama-3.1-405b-instruct", "name": "llama-3.1-405b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "grok",
        "display_name": "xAI Grok",
        "provider_type": "openai",
        "api_base": "https://api.x.ai",
        "default_model": "grok-4",
        "models": [
            {"id": "grok-4", "name": "Grok 4", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "grok-3", "name": "Grok 3", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "grok-3-fast", "name": "Grok 3 Fast", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "grok-3-mini", "name": "Grok 3 Mini", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "grok-3-mini-fast", "name": "Grok 3 Mini Fast", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "hyperbolic",
        "display_name": "Hyperbolic",
        "provider_type": "openai",
        "api_base": "https://api.hyperbolic.xyz",
        "default_model": "Qwen/Qwen2-VL-72B-Instruct",
        "models": [
            {"id": "Qwen/Qwen2-VL-72B-Instruct", "name": "Qwen2-VL-72B-Instruct", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "Qwen/Qwen2-VL-7B-Instruct", "name": "Qwen2-VL-7B-Instruct", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "mistralai/Pixtral-12B-2409", "name": "Pixtral-12B-2409", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "meta-llama/Meta-Llama-3.1-405B", "name": "Meta-Llama-3.1-405B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "perplexity",
        "display_name": "Perplexity",
        "provider_type": "openai",
        "api_base": "https://api.perplexity.ai",
        "default_model": "sonar-reasoning-pro",
        "models": [
            {"id": "sonar-reasoning-pro", "name": "sonar-reasoning-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "sonar-reasoning", "name": "sonar-reasoning", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "sonar-pro", "name": "sonar-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "sonar", "name": "sonar", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "sonar-deep-research", "name": "sonar-deep-research", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "huggingface",
        "display_name": "Hugging Face",
        "provider_type": "openai-response",
        "api_base": "https://router.huggingface.co/v1",
        "default_model": "",
        "models": [],
    },
    {
        "id": "cerebras",
        "display_name": "Cerebras",
        "provider_type": "openai",
        "api_base": "https://api.cerebras.ai/v1",
        "default_model": "gpt-oss-120b",
        "models": [
            {"id": "gpt-oss-120b", "name": "GPT oss 120B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "zai-glm-4.6", "name": "GLM 4.6", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-3-235b-a22b-instruct-2507", "name": "Qwen 3 235B A22B Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "yi",
        "display_name": "零一万物",
        "provider_type": "openai",
        "api_base": "https://api.lingyiwanwu.com",
        "default_model": "yi-lightning",
        "models": [
            {"id": "yi-lightning", "name": "Yi Lightning", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "yi-vision-v2", "name": "Yi Vision v2", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "jina",
        "display_name": "Jina AI",
        "provider_type": "openai",
        "api_base": "https://api.jina.ai",
        "default_model": "jina-clip-v1",
        "models": [
            {"id": "jina-clip-v1", "name": "jina-clip-v1", "model_type": "vision", "context_window": 8192, "supports_function_calling": False, "supports_vision": True, "max_tokens": 8192},
            {"id": "jina-clip-v2", "name": "jina-clip-v2", "model_type": "vision", "context_window": 8192, "supports_function_calling": False, "supports_vision": True, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-en", "name": "jina-embeddings-v2-base-en", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-es", "name": "jina-embeddings-v2-base-es", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-de", "name": "jina-embeddings-v2-base-de", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-zh", "name": "jina-embeddings-v2-base-zh", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-code", "name": "jina-embeddings-v2-base-code", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v3", "name": "jina-embeddings-v3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "poe",
        "display_name": "Poe",
        "provider_type": "openai",
        "api_base": "https://api.poe.com/v1",
        "default_model": "gpt-4o",
        "models": [
            {"id": "gpt-4o", "name": "GPT-4o", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "aws-bedrock",
        "display_name": "AWS Bedrock",
        "provider_type": "aws-bedrock",
        "api_base": "",
        "default_model": "",
        "models": [],
    },
    {
        "id": "voyageai",
        "display_name": "Voyage AI",
        "provider_type": "openai",
        "api_base": "https://api.voyageai.com",
        "default_model": "voyage-3-large",
        "models": [
            {"id": "voyage-3-large", "name": "voyage-3-large", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-3", "name": "voyage-3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-3-lite", "name": "voyage-3-lite", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-code-3", "name": "voyage-code-3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-finance-3", "name": "voyage-finance-3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-law-2", "name": "voyage-law-2", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "voyage-code-2", "name": "voyage-code-2", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "rerank-2", "name": "rerank-2", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "rerank-2-lite", "name": "rerank-2-lite", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "gpustack",
        "display_name": "GPUStack",
        "provider_type": "openai",
        "api_base": "",
        "default_model": "",
        "models": [],
    },
    {
        "id": "gateway",
        "display_name": "Vercel AI Gateway",
        "provider_type": "gateway",
        "api_base": "https://ai-gateway.vercel.sh/v1/ai",
        "default_model": "",
        "models": [],
    },
    {
        "id": "mimo",
        "display_name": "小米MiMo",
        "provider_type": "openai",
        "api_base": "https://api.xiaomimimo.com",
        "default_model": "mimo-v2-flash",
        "models": [
            {"id": "mimo-v2-flash", "name": "Mimo V2 Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "modelscope",
        "display_name": "ModelScope",
        "provider_type": "openai",
        "api_base": "https://api-inference.modelscope.cn/v1",
        "default_model": "Qwen/Qwen2.5-72B-Instruct",
        "models": [
            {"id": "Qwen/Qwen2.5-72B-Instruct", "name": "Qwen/Qwen2.5-72B-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Qwen/Qwen2.5-VL-72B-Instruct", "name": "Qwen/Qwen2.5-VL-72B-Instruct", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "Qwen/Qwen2.5-Coder-32B-Instruct", "name": "Qwen/Qwen2.5-Coder-32B-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-ai/DeepSeek-R1", "name": "deepseek-ai/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-ai/DeepSeek-V3", "name": "deepseek-ai/DeepSeek-V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "xirang",
        "display_name": "羲和",
        "provider_type": "openai",
        "api_base": "https://wishub-x1.ctyun.cn",
        "default_model": "",
        "models": [],
    },
    {
        "id": "hunyuan",
        "display_name": "腾讯混元",
        "provider_type": "openai",
        "api_base": "https://api.hunyuan.cloud.tencent.com",
        "default_model": "hunyuan-pro",
        "models": [
            {"id": "hunyuan-pro", "name": "hunyuan-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-standard", "name": "hunyuan-standard", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-lite", "name": "hunyuan-lite", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-standard-256k", "name": "hunyuan-standard-256k", "model_type": "chat", "context_window": 262144, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-vision", "name": "hunyuan-vision", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "hunyuan-code", "name": "hunyuan-code", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-role", "name": "hunyuan-role", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-turbo", "name": "hunyuan-turbo", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-turbos-latest", "name": "hunyuan-turbos-latest", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "hunyuan-embedding", "name": "hunyuan-embedding", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "tencent-cloud-ti",
        "display_name": "腾讯云TI",
        "provider_type": "openai",
        "api_base": "https://api.lkeap.cloud.tencent.com",
        "default_model": "deepseek-r1",
        "models": [
            {"id": "deepseek-r1", "name": "DeepSeek R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3", "name": "DeepSeek V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "baidu-cloud",
        "display_name": "百度智能云",
        "provider_type": "openai",
        "api_base": "https://qianfan.baidubce.com/v2",
        "default_model": "deepseek-r1",
        "models": [
            {"id": "deepseek-r1", "name": "DeepSeek R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3", "name": "DeepSeek V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ernie-4.0-8k-latest", "name": "ERNIE-4.0", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ernie-4.0-turbo-8k-latest", "name": "ERNIE 4.0 Turbo", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ernie-speed-8k", "name": "ERNIE Speed", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ernie-lite-8k", "name": "ERNIE Lite", "model_type": "chat", "context_window": 8192, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "bge-large-zh", "name": "BGE Large ZH", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "bge-large-en", "name": "BGE Large EN", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "302ai",
        "display_name": "302.AI",
        "provider_type": "openai",
        "api_base": "https://api.302.ai",
        "default_model": "deepseek-chat",
        "models": [
            {"id": "deepseek-chat", "name": "deepseek-chat", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-reasoner", "name": "deepseek-reasoner", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "chatgpt-4o-latest", "name": "chatgpt-4o-latest", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4.1", "name": "gpt-4.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "o3", "name": "o3", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "o4-mini", "name": "o4-mini", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen3-235b-a22b", "name": "qwen3-235b-a22b", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gemini-2.5-flash-preview-05-20", "name": "gemini-2.5-flash-preview-05-20", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-pro-preview-06-05", "name": "gemini-2.5-pro-preview-06-05", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-sonnet-4-20250514", "name": "claude-sonnet-4-20250514", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-opus-4-20250514", "name": "claude-opus-4-20250514", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "jina-clip-v2", "name": "jina-clip-v2", "model_type": "vision", "context_window": 32768, "supports_function_calling": False, "supports_vision": True, "max_tokens": 8192},
            {"id": "jina-reranker-m0", "name": "jina-reranker-m0", "model_type": "embedding", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "dmxapi",
        "display_name": "DMXAPI",
        "provider_type": "openai",
        "api_base": "https://www.dmxapi.cn",
        "default_model": "Qwen/Qwen2.5-7B-Instruct",
        "models": [
            {"id": "Qwen/Qwen2.5-7B-Instruct", "name": "Qwen/Qwen2.5-7B-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "ERNIE-Speed-128K", "name": "ERNIE-Speed-128K", "model_type": "chat", "context_window": 131072, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-4o", "name": "gpt-4o", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4o-mini", "name": "gpt-4o-mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "DMXAPI-DeepSeek-R1", "name": "DMXAPI-DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "DMXAPI-DeepSeek-V3", "name": "DMXAPI-DeepSeek-V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "claude-3-5-sonnet-20241022", "name": "claude-3-5-sonnet-20241022", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-2.0-flash", "name": "gemini-2.0-flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "ppio",
        "display_name": "PPIO",
        "provider_type": "openai",
        "api_base": "https://api.ppinfra.com/v3/openai",
        "default_model": "deepseek/deepseek-v3.2",
        "models": [
            {"id": "deepseek/deepseek-v3.2", "name": "DeepSeek V3.2", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "minimax/minimax-m2", "name": "MiniMax M2", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen/qwen3-235b-a22b-instruct-2507", "name": "Qwen3-235b-a22b-instruct-2507", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen/qwen3-vl-235b-a22b-instruct", "name": "Qwen3-vl-235b-a22b-instruct", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "qwen/qwen3-embedding-8b", "name": "Qwen3 Embedding 8B", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "qwen/qwen3-reranker-8b", "name": "Qwen3 Reranker 8B", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "qiniu",
        "display_name": "七牛云",
        "provider_type": "openai",
        "api_base": "https://api.qnaigc.com",
        "default_model": "deepseek-r1",
        "models": [
            {"id": "deepseek-r1", "name": "DeepSeek R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-search", "name": "DeepSeek R1 Search", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-32b", "name": "DeepSeek R1 32B", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3", "name": "DeepSeek V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3-search", "name": "DeepSeek V3 Search", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3-tool", "name": "DeepSeek V3 Tool", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwq-32b", "name": "QWQ 32B", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-72b-instruct", "name": "Qwen2.5 72B Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "tokenflux",
        "display_name": "TokenFlux",
        "provider_type": "openai",
        "api_base": "https://api.tokenflux.ai/openai/v1",
        "default_model": "gpt-4.1",
        "models": [
            {"id": "gpt-4.1", "name": "GPT-4.1", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-4.1-mini", "name": "GPT-4.1 Mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "claude-sonnet-4", "name": "Claude Sonnet 4", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-3-7-sonnet", "name": "Claude 3.7 Sonnet", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash", "model_type": "chat", "context_window": 1048576, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "deepseek-r1", "name": "DeepSeek R1", "model_type": "chat", "context_window": 128000, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3", "name": "DeepSeek V3", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-max", "name": "Qwen Max", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen-plus", "name": "Qwen Plus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "alayanew",
        "display_name": "AlayaNew",
        "provider_type": "openai",
        "api_base": "https://deepseek.alayanew.com",
        "default_model": "",
        "models": [],
    },
    {
        "id": "aionly",
        "display_name": "AIOnly",
        "provider_type": "openai",
        "api_base": "https://api.aiionly.com",
        "default_model": "claude-opus-4-5-20251101",
        "models": [
            {"id": "claude-opus-4-5-20251101", "name": "Claude Opus 4.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-haiku-4-5-20251001", "name": "Claude Haiku 4.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-sonnet-4-5-20250929", "name": "Claude Sonnet 4.5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-5.1", "name": "GPT-5.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.1-chat", "name": "GPT-5.1 Chat", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5-pro", "name": "GPT 5 Pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gemini-3-pro-preview", "name": "Gemini 3 Pro Preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
        ],
    },
    {
        "id": "burncloud",
        "display_name": "BurnCloud",
        "provider_type": "openai",
        "api_base": "https://ai.burncloud.com",
        "default_model": "claude-opus-4-5-20251101",
        "models": [
            {"id": "claude-opus-4-5-20251101", "name": "Claude 4.5 Opus", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-sonnet-4-5-20250929", "name": "Claude 4.5 Sonnet", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "claude-haiku-4-5-20251001", "name": "Claude 4.5 Haiku", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-5", "name": "GPT 5", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-5.1", "name": "GPT 5.1", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "gemini-2.5-flash", "name": "Gemini 2.5 Flash", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-flash-image", "name": "Gemini 2.5 Flash Image", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-2.5-pro", "name": "Gemini 2.5 Pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-3-pro-preview", "name": "Gemini 3 Pro Preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "deepseek-reasoner", "name": "DeepSeek Reasoner", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-chat", "name": "DeepSeek Chat", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "cephalon",
        "display_name": "Cephalon",
        "provider_type": "openai",
        "api_base": "https://cephalon.cloud/user-center/v1/model",
        "default_model": "DeepSeek-R1",
        "models": [
            {"id": "DeepSeek-R1", "name": "DeepSeek-R1满血版", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "lanyun",
        "display_name": "蓝云",
        "provider_type": "openai",
        "api_base": "https://maas-api.lanyun.net",
        "default_model": "/maas/deepseek-ai/DeepSeek-R1-0528",
        "models": [
            {"id": "/maas/deepseek-ai/DeepSeek-R1-0528", "name": "deepseek-ai/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "/maas/deepseek-ai/DeepSeek-V3-0324", "name": "deepseek-ai/DeepSeek-V3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "/maas/qwen/Qwen2.5-72B-Instruct", "name": "Qwen2.5-72B-Instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "/maas/qwen/Qwen3-235B-A22B", "name": "Qwen/Qwen3-235B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "/maas/minimax/MiniMax-M1-80k", "name": "MiniMax-M1-80k", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "/maas/google/Gemma3-27B", "name": "Gemma3-27B", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "ph8",
        "display_name": "PH8",
        "provider_type": "openai",
        "api_base": "https://ph8.co",
        "default_model": "deepseek-v3-241226",
        "models": [
            {"id": "deepseek-v3-241226", "name": "deepseek-v3-241226", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-250120", "name": "deepseek-r1-250120", "model_type": "chat", "context_window": 128000, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "sophnet",
        "display_name": "SophNet",
        "provider_type": "openai",
        "api_base": "https://www.sophnet.com/api/open-apis/v1",
        "default_model": "",
        "models": [],
    },
    {
        "id": "ovms",
        "display_name": "OpenVINO Model Server",
        "provider_type": "openai",
        "api_base": "http://localhost:8000/v3",
        "default_model": "",
        "models": [],
    },
    {
        "id": "ocoolai",
        "display_name": "ocoolAI",
        "provider_type": "openai",
        "api_base": "https://api.ocoolai.com",
        "default_model": "deepseek-chat",
        "models": [
            {"id": "deepseek-chat", "name": "deepseek-chat", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-reasoner", "name": "deepseek-reasoner", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-ai/DeepSeek-R1", "name": "deepseek-ai/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "HiSpeed/DeepSeek-R1", "name": "HiSpeed/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "ocoolAI/DeepSeek-R1", "name": "ocoolAI/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "Azure/DeepSeek-R1", "name": "Azure/DeepSeek-R1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "gpt-4o", "name": "gpt-4o", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4o-all", "name": "gpt-4o-all", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4o-mini", "name": "gpt-4o-mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gpt-4", "name": "gpt-4", "model_type": "chat", "context_window": 128000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "o1-preview", "name": "o1-preview", "model_type": "chat", "context_window": 128000, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "o1-mini", "name": "o1-mini", "model_type": "chat", "context_window": 128000, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "claude-3-5-sonnet-20240620", "name": "claude-3-5-sonnet-20240620", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "claude-3-5-haiku-20241022", "name": "claude-3-5-haiku-20241022", "model_type": "chat", "context_window": 200000, "supports_function_calling": True, "supports_vision": True, "max_tokens": 8192},
            {"id": "gemini-pro", "name": "gemini-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "gemini-1.5-pro", "name": "gemini-1.5-pro", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo", "name": "Llama-3.2-90B-Vision-Instruct-Turbo", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo", "name": "Llama-3.2-11B-Vision-Instruct-Turbo", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "meta-llama/Llama-3.2-3B-Vision-Instruct-Turbo", "name": "Llama-3.2-3B-Vision-Instruct-Turbo", "model_type": "vision", "context_window": 32768, "supports_function_calling": True, "supports_vision": True, "max_tokens": 4096},
            {"id": "google/gemma-2-27b-it", "name": "gemma-2-27b-it", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "google/gemma-2-9b-it", "name": "gemma-2-9b-it", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "Doubao-embedding", "name": "Doubao-embedding", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-3-large", "name": "text-embedding-3-large", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-3-small", "name": "text-embedding-3-small", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "text-embedding-v2", "name": "text-embedding-v2", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "infini",
        "display_name": "Infini",
        "provider_type": "openai",
        "api_base": "https://cloud.infini-ai.com/maas",
        "default_model": "deepseek-r1",
        "models": [
            {"id": "deepseek-r1", "name": "deepseek-r1", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-r1-distill-qwen-32b", "name": "deepseek-r1-distill-qwen-32b", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "deepseek-v3", "name": "deepseek-v3", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-72b-instruct", "name": "qwen2.5-72b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-32b-instruct", "name": "qwen2.5-32b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-14b-instruct", "name": "qwen2.5-14b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-7b-instruct", "name": "qwen2.5-7b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2-72b-instruct", "name": "qwen2-72b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwq-32b-preview", "name": "qwq-32b-preview", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
            {"id": "qwen2.5-coder-32b-instruct", "name": "qwen2.5-coder-32b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "llama-3.3-70b-instruct", "name": "llama-3.3-70b-instruct", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "bge-m3", "name": "bge-m3", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "gemma-2-27b-it", "name": "gemma-2-27b-it", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "jina-embeddings-v2-base-zh", "name": "jina-embeddings-v2-base-zh", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
            {"id": "jina-embeddings-v2-base-code", "name": "jina-embeddings-v2-base-code", "model_type": "embedding", "context_window": 8192, "supports_function_calling": False, "supports_vision": False, "max_tokens": 8192},
        ],
    },
    {
        "id": "longcat",
        "display_name": "LongCat",
        "provider_type": "openai",
        "api_base": "https://api.longcat.chat/openai",
        "default_model": "LongCat-Flash-Chat",
        "models": [
            {"id": "LongCat-Flash-Chat", "name": "LongCat Flash Chat", "model_type": "chat", "context_window": 32768, "supports_function_calling": True, "supports_vision": False, "max_tokens": 4096},
            {"id": "LongCat-Flash-Thinking", "name": "LongCat Flash Thinking", "model_type": "chat", "context_window": 32768, "supports_function_calling": False, "supports_vision": False, "max_tokens": 4096},
        ],
    },
    {
        "id": "new-api",
        "display_name": "New API",
        "provider_type": "new-api",
        "api_base": "http://localhost:3000",
        "default_model": "",
        "models": [],
    },
]
